// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostTripRouteBadRequestBody post trip route bad request body
//
// swagger:model postTripRouteBadRequestBody
type PostTripRouteBadRequestBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this post trip route bad request body
func (m *PostTripRouteBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post trip route bad request body based on context it is used
func (m *PostTripRouteBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostTripRouteBadRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostTripRouteBadRequestBody) UnmarshalBinary(b []byte) error {
	var res PostTripRouteBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
